### ISSUE TITLE
Link to the docs is broken or private

### ISSUE THREAD

**Issue by emmanuel-contreras** [LaboratoryOpticsBiosciences/FLUTE#3]
Hello,
I wanted to read the docs to learn how to use your tool but the link on the readme that points to the docs appears to be broken or private.

https://github.com/DaleLOB/FLUTE

Thank you,

 - Emmanuel

**Comment by ChiaraStringari** [comment]
Hi Emmanuel,
You can find the description of the software and the user manual in the preprint:
"FLUTE: a Python GUI for interactive phasor analysis of FLIM data"
https://www.biorxiv.org/content/10.1101/2023.03.31.534529v1

We fixed the link "Explore the docs"

Chiara

**Comment by emmanuel-contreras** [comment]
awesome, thank you!
